In [1]:
import pandas as pd
from bs4 import BeautifulSoup as bs

In [56]:
df = pd.read_csv('../data/result_deep.csv')

In [57]:
df.drop(
    ['employment', 'specializations', 'published_at', 
     'created_at', 'apply_alternate_url', 'gross', 'professional_roles'], 
    axis=1, 
    inplace=True
    )

In [58]:
df[df['languages'].notnull()]

,id,name,area,experience,description,key_skills,employer,alternate_url,languages,from,to,currency
2,70449444,Data Analyst (Remote),Турция,От 3 до 6 лет,Novakid приглашает ведущего продуктового анали...,"['SQL', 'Python', 'Tableau', 'Английский язык'...",Novakid Inc,https://hh.ru/vacancy/70449444,"[{'id': 'eng', 'name': 'Английский', 'level': ...",4500.0,NaN,USD
6,70449445,Data Analyst (Remote),Москва,От 3 до 6 лет,Novakid приглашает ведущего продуктового анали...,"['SQL', 'Python', 'Tableau', 'Английский язык'...",Novakid Inc,https://hh.ru/vacancy/70449445,"[{'id': 'eng', 'name': 'Английский', 'level': ...",4500.0,NaN,USD
9,70858530,Разработчик Python,Москва,Более 6 лет,Обязанности: Разработка back-end решений в ме...,"['Django Framework', 'PostgreSQL', 'Redis', 'S...",Кадровый холдинг ПРОФИЛЬ,https://hh.ru/vacancy/70858530,"[{'id': 'eng', 'name': 'Английский', 'level': ...",350000.0,NaN,RUR
12,70449443,Data Analyst (Remote),Санкт-Петербург,От 3 до 6 лет,Novakid приглашает ведущего продуктового анали...,"['SQL', 'Python', 'Tableau', 'Английский язык'...",Novakid Inc,https://hh.ru/vacancy/70449443,"[{'id': 'eng', 'name': 'Английский', 'level': ...",4500.0,NaN,USD
18,70709226,Python-разработчик,Москва,От 3 до 6 лет,"О НАС EPG SERVICE - международная компания, со...","['API', 'Kafka', 'Python', 'NixOS', 'Git', 'Po...",EPG Service,https://hh.ru/vacancy/70709226,"[{'id': 'eng', 'name': 'Английский', 'level': ...",120000.0,150000.0,RUR
24,69454163,Python Developer (DWH),Москва,От 1 года до 3 лет,"Emerging Travel Group — travel-tech компания, ...","['Python', 'PostgreSQL']","Emerging Travel Group (Ostrovok.ru, B2B.Ostrov...",https://hh.ru/vacancy/69454163,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
26,69869831,Программист Python (Senior),Москва,Более 6 лет,Описание вакансии Smart Technologies - компани...,"['Git', 'Linux', 'ООП', 'Django Framework', 'P...","Смарт Текнолоджис,ООО",https://hh.ru/vacancy/69869831,"[{'id': 'eng', 'name': 'Английский', 'level': ...",300000.0,NaN,RUR
29,70736925,Python Developer,Батуми,От 3 до 6 лет,"Andersen, an international IT company, invites...","['Django Framework', 'Python', 'Git', 'Postgre...",Andersen,https://hh.ru/vacancy/70736925,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
34,69454225,Python Developer (Extranet Team),Москва,От 1 года до 3 лет,"Emerging Travel Group — travel-tech компания, ...","['Python', 'SQL']","Emerging Travel Group (Ostrovok.ru, B2B.Ostrov...",https://hh.ru/vacancy/69454225,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
42,70911556,Senior Python developer,Москва,От 3 до 6 лет,Nitka Technologies занимается разработкой ПО д...,"['Python', 'Rust', 'Английский язык', 'Big Dat...",Nitka Technologies,https://hh.ru/vacancy/70911556,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
52,70911562,Senior Python developer,Тбилиси,От 3 до 6 лет,Nitka Technologies занимается разработкой ПО д...,"['Python', 'Rust', 'Английский язык', 'Big Dat...",Nitka Technologies,https://hh.ru/vacancy/70911562,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
54,70911558,Senior Python developer,Армения,От 3 до 6 лет,Nitka Technologies занимается разработкой ПО д...,"['Python', 'Rust', 'Английский язык', 'Big Dat...",Nitka Technologies,https://hh.ru/vacancy/70911558,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
62,68790008,R Developer,Тбилиси,От 3 до 6 лет,В математический проект требуется R разработчи...,"['Python', 'R', 'MongoDB', 'SQL', 'Numpy', 'Pa...",HiQo Solutions,https://hh.ru/vacancy/68790008,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
63,70911563,Senior Python developer,Астана,От 3 до 6 лет,Nitka Technologies занимается разработкой ПО д...,"['Python', 'Rust', 'Английский язык', 'Big Dat...",Nitka Technologies,https://hh.ru/vacancy/70911563,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
75,69594554,Team Lead (Python),Санкт-Петербург,От 3 до 6 лет,Немного о нас:TradeTech Development занимается...,"['Python', 'Git', 'PostgreSQL', 'SQL', 'Linux']",Tradetech Development,https://hh.ru/vacancy/69594554,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
107,70584200,Senior Python Developer (remote),Армения,Более 6 лет,CoinLoan – платформа управления цифровыми акти...,"['Python', 'Django', 'Django Framework', 'Асин...",Коинлоан,https://hh.ru/vacancy/70584200,"[{'id': 'eng', 'name': 'Английский', 'level': ...",4000.0,NaN,EUR
108,55088580,"Разработчик Python (Middle, Senior)",Москва,От 3 до 6 лет,"Мы - компания NGENIX, крупнейшая в России расп...","['Python', 'PostgreSQL', 'SQL', 'MySQL', 'Scrum']",NGENIX,https://hh.ru/vacancy/55088580,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
110,70401826,"Backend-разработчик (Python)/Риск-менеджмент, ...",Санкт-Петербург,От 1 года до 3 лет,Что ты будешь делать в этой роли: Присоединивш...,"['Python', 'Git', 'PostgreSQL', 'Django Framew...",Деловые Решения и Технологии (ДРТ),https://hh.ru/vacancy/70401826,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
111,69872911,Python Developer (Partners),Москва,От 3 до 6 лет,"Emerging Travel Group — travel-tech компания, ...","['Git', 'Python', 'Django Framework', 'Docker']","Emerging Travel Group (Ostrovok.ru, B2B.Ostrov...",https://hh.ru/vacancy/69872911,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
115,70015953,Senior Python Developer,Армения,Более 6 лет,Мы - американская технологическая компания с р...,"['Python', 'SQLAlchemy', 'Английский язык']",IT and Digital,https://hh.ru/vacancy/70015953,"[{'id': 'eng', 'name': 'Английский', 'level': ...",6000.0,NaN,USD
119,70401754,"Backend-разработчик (Python)/Риск-менеджмент, ...",Москва,От 1 года до 3 лет,Что ты будешь делать в этой роли: Присоединивш...,"['Python', 'Git', 'PostgreSQL', 'Django Framew...",Деловые Решения и Технологии (ДРТ),https://hh.ru/vacancy/70401754,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
120,70401965,Backend-разработчик (Python)/Риск-менеджмент (...,Уфа,От 1 года до 3 лет,Что ты будешь делать в этой роли: Присоединивш...,"['Python', 'Git', 'PostgreSQL', 'Django Framew...",Деловые Решения и Технологии (ДРТ),https://hh.ru/vacancy/70401965,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
122,70401918,"Backend-разработчик (Python)/Риск-менеджмент, ...",Новосибирск,От 1 года до 3 лет,Что ты будешь делать в этой роли: Присоединивш...,"['Python', 'Git', 'PostgreSQL', 'Django Framew...",Деловые Решения и Технологии (ДРТ),https://hh.ru/vacancy/70401918,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
123,70348228,Senior/Middle Python разработчик,Москва,От 3 до 6 лет,Наша финтех-компания “Деньги Вперед” активно р...,"['Python', 'Flask', 'Django Framework', 'Djang...",Деньги Вперед,https://hh.ru/vacancy/70348228,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
126,70348277,Lead Python разработчик,Москва,Более 6 лет,Наша финтех-компания “Деньги Вперед” активно р...,"['Python', 'Flask', 'Django Framework', 'Djang...",Деньги Вперед,https://hh.ru/vacancy/70348277,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
128,70401938,"Backend-разработчик (Python)/Риск-менеджмент, ...",Екатеринбург,От 1 года до 3 лет,Что ты будешь делать в этой роли: Присоединивш...,"['Python', 'Git', 'PostgreSQL', 'Django Framew...",Деловые Решения и Технологии (ДРТ),https://hh.ru/vacancy/70401938,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
129,69895621,Python Backend Разработчик,Астана,От 3 до 6 лет,Python Backend Разработчик Обязанности: Оптим...,"['Git', 'Postman', 'REST API', 'Figma', 'MVC',...",Adizit,https://hh.ru/vacancy/69895621,"[{'id': 'eng', 'name': 'Английский', 'level': ...",400000.0,800000.0,KZT
154,66954468,Senior Python Developer,Алматы,От 3 до 6 лет,PROJECT OVERVIEW Teams that need Python develo...,"['Python', 'Django Framework', 'Flask', 'HTML5...",DataArt,https://hh.ru/vacancy/66954468,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
157,70911561,Senior Python developer,Кишинёв,От 3 до 6 лет,Nitka Technologies занимается разработкой ПО д...,"['Python', 'Rust', 'Английский язык', 'Big Dat...",Nitka Technologies,https://hh.ru/vacancy/70911561,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
158,69978113,Data engineer (Middle),Москва,От 1 года до 3 лет,Что и как мы делаем? Мы создаем продвинутое ...,"['SQL', 'SCALA', 'Linux', 'Работа в команде', ...",билайн,https://hh.ru/vacancy/69978113,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
159,69474938,Senior Python Developer (Partners),Москва,От 3 до 6 лет,"Emerging Travel Group — travel-tech компания, ...","['SQL', 'Python']","Emerging Travel Group (Ostrovok.ru, B2B.Ostrov...",https://hh.ru/vacancy/69474938,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
178,70364815,DevOps инженер Smart Data,Москва,От 1 года до 3 лет,Мы ищем DevOps инженера в команду Smart Data.С...,"['Linux', 'Bash', 'Nginx', 'Docker', 'SQL', 'D...",Банк Хоум Кредит,https://hh.ru/vacancy/70364815,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
182,70029182,Senior Python Developer (Extranet Team),Москва,От 3 до 6 лет,"Emerging Travel Group — travel-tech компания, ...","['Python', 'Golang']","Emerging Travel Group (Ostrovok.ru, B2B.Ostrov...",https://hh.ru/vacancy/70029182,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
183,69823794,Senior Software engineer (Python),Москва,Более 6 лет,Нужен Software Engineer в международную компан...,"['Python', 'C++', 'API', 'Multithreading', 'Mu...","Hi, Rockits!",https://hh.ru/vacancy/69823794,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
197,49488972,Программист Python,Ростов-на-Дону,От 1 года до 3 лет,Какие задачи Вам предстоит решать: Разработка...,"['Python', 'Git', 'Linux', 'Английский язык', ...",Электронная медицина,https://hh.ru/vacancy/49488972,"[{'id': 'eng', 'name': 'Английский', 'level': ...",50000.0,200000.0,RUR
203,70736176,DevOps Engineer,Москва,От 1 года до 3 лет,About Company: Leadex Systems - консалтинговая...,"['Graphana', 'CentOS', 'RHEL', 'Nagios', 'Zabb...",Лидекс Системс,https://hh.ru/vacancy/70736176,"[{'id': 'eng', 'name': 'Английский', 'level': ...",250000.0,NaN,RUR
205,69924752,DevOps engineer,Москва,От 3 до 6 лет,Greenscreens.ai is SaaS platform offering ML a...,"['DevOps', 'Gitlab CI', 'Kubernetes', 'Linux',...",Greenscreens.AI,https://hh.ru/vacancy/69924752,"[{'id': 'eng', 'name': 'Английский', 'level': ...",3000.0,NaN,EUR
212,69960826,Senior Backend Engineer,Москва,От 3 до 6 лет,Adapty helps mobile developers to increase rev...,"['Python', 'SQL', 'PostgreSQL', 'Английский яз...",Adapty,https://hh.ru/vacancy/69960826,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,5500.0,USD
218,70846212,ETL/DWH developer,Москва,От 3 до 6 лет,"Emerging Travel Group — travel-tech компания, ...","['Python', 'SQL', 'PostgreSQL', 'Git', 'ETL', ...","Emerging Travel Group (Ostrovok.ru, B2B.Ostrov...",https://hh.ru/vacancy/70846212,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
220,70817034,"Руководитель группы разработки, Tech Lead кома...",Москва,Более 6 лет,MTS AI это отдельная IT-компания внутри экосис...,"['Python', 'Разработка ПО', 'Управление команд...",МТС,https://hh.ru/vacancy/70817034,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
227,69962147,Senior DevOps Engineer (Serbia),Москва,От 3 до 6 лет,"We are looking for a Senior DevOps Engineer, s...","['Docker', 'Kubernetes', 'Helm', 'Terraform', ...",Schaffhausen Institute of Technology,https://hh.ru/vacancy/69962147,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
228,70788880,DevOps Engineer,Новосибирск,От 1 года до 3 лет,LC Group – международная IT-компания из Сибири...,"['Linux', 'Python', 'Английский язык', 'Grafan...",LC Group,https://hh.ru/vacancy/70788880,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
230,69089392,ETL Разработчик-Консультант,Москва,От 3 до 6 лет,Описание проекта: Крупнейший банк РФ продолжае...,"['Hadoop', 'ETL', 'SQL', 'Spark', 'Java', 'Pyt...",Bell Integrator,https://hh.ru/vacancy/69089392,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
232,70807448,Site Reliability Engineer (SRE) / Software Eng...,Москва,От 3 до 6 лет,Tabby makes shopping more rewarding by empower...,"['Docker', 'Golang', 'Английский язык', 'SQL',...",Tabby,https://hh.ru/vacancy/70807448,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
240,70332323,Site Reliability Engineer,Алматы,От 3 до 6 лет,POSITION OVERVIEW DataArt's SRE Center of Comp...,"['Linux', 'Python', 'Docker', 'Bash', 'Prometh...",DataArt,https://hh.ru/vacancy/70332323,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
242,70210554,Senior/Middle DevOps,Тбилиси,От 1 года до 3 лет,About company We are a professional services c...,"['Docker', 'Bash', 'Linux', 'Python', 'Kuberne...",Lembit LLC,https://hh.ru/vacancy/70210554,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
250,70135087,Senior DevOps Engineer,Астана,От 3 до 6 лет,CLIENT Our Client is a US company. The Client ...,"['AWS', 'Jenkins', 'Git', 'Java', 'SQL']",DataArt,https://hh.ru/vacancy/70135087,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
251,70135086,Senior DevOps Engineer,Алматы,От 3 до 6 лет,CLIENT Our Client is a US company. The Client ...,"['AWS', 'Jenkins', 'Git', 'Java', 'SQL']",DataArt,https://hh.ru/vacancy/70135086,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
252,70135088,Senior DevOps Engineer,Караганда,От 3 до 6 лет,CLIENT Our Client is a US company. The Client ...,"['AWS', 'Jenkins', 'Git', 'Java', 'SQL']",DataArt,https://hh.ru/vacancy/70135088,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
254,67488445,Senior Data Scientist,Казань,От 3 до 6 лет,Мы аккредитованная IT-компания. ICL Services р...,"['Математическая статистика', 'ML', 'Machine L...",ICL Services,https://hh.ru/vacancy/67488445,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
264,69423179,QA Engineer (GKT Team),Армения,От 3 до 6 лет,"Hi there!We are Semrush, a global IT company d...","['Python', 'Bash', 'Linux', 'SQL', 'Docker', '...",Semrush,https://hh.ru/vacancy/69423179,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
273,70507277,Team Lead NLP Engineer,Астана,От 3 до 6 лет,"Ищем тимлида в команду NLP Диалоговых систем, ...","['Python', 'NLP', 'Machine Learning', 'ML', 'D...",Тинькофф,https://hh.ru/vacancy/70507277,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
274,69297098,DevOps Team Lead,Москва,От 3 до 6 лет,"Emerging Travel Group — travel-tech компания, ...","['Python', 'Linux', 'PostgreSQL', 'Ansible']","Emerging Travel Group (Ostrovok.ru, B2B.Ostrov...",https://hh.ru/vacancy/69297098,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
278,70406313,Unreal Engine Developer (Remote),Москва,От 1 года до 3 лет,Компания ICVR https://icvr.io/ приглашает к со...,"['Git', 'C++', 'Blueprints', 'Python', 'Qt', '...",ICVR,https://hh.ru/vacancy/70406313,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
286,70357826,DevOps,Москва,От 1 года до 3 лет,IT Product Office (ITPO) - международная компа...,"['DevOps', 'Kubernetes', 'PostgreSQL', 'AWS']",ITPO group,https://hh.ru/vacancy/70357826,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
289,70332283,Site Reliability Engineer,Астана,От 3 до 6 лет,POSITION OVERVIEW DataArt's SRE Center of Comp...,"['Linux', 'Python', 'Docker', 'Bash', 'Prometh...",DataArt,https://hh.ru/vacancy/70332283,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN
299,70158920,DevOps Engineer,Алматы,От 1 года до 3 лет,Мы приглашаем в свою команду специалистов и ра...,"['Английский язык', 'Docker', 'Kubernetes', 'A...",PLAVNO (ПЛАВНО),https://hh.ru/vacancy/70158920,"[{'id': 'eng', 'name': 'Английский', 'level': ...",2000.0,3500.0,USD
315,69859250,Data Engineer,Москва,От 3 до 6 лет,На стартовавший проект Altenar Intelligence Pl...,"['Git', 'Kubernetes', 'Spark', 'Business intel...",Altenar,https://hh.ru/vacancy/69859250,"[{'id': 'eng', 'name': 'Английский', 'level': ...",NaN,NaN,NaN

In [59]:
df.drop(df[df['languages'].notnull()].index, inplace=True)

In [60]:
df.drop(['languages'], axis=1, inplace=True)

In [61]:
df.sort_values(by=['employer'], inplace=True)

In [62]:
df

,id,name,area,experience,description,key_skills,employer,alternate_url,from,to,currency
88,70472405,Python Developer,Петропавловка (Республика Бурятия),От 3 до 6 лет,"2people IT ― компания, предоставляющая техноло...","['Python', 'Django Framework', 'PostgreSQL', '...",2people IT,https://hh.ru/vacancy/70472405,NaN,NaN,NaN
134,69695405,ETL-разработчик (уровень не ниже среднего),Москва,От 3 до 6 лет,Удалённая работа Обязанности: Дизайн и разраб...,"['Python', 'PostgreSQL', 'SQL', 'MS SQL Server...",7RedLines,https://hh.ru/vacancy/69695405,140000.0,180000.0,RUR
131,70348684,Ведущий разработчик Python,Москва,От 3 до 6 лет,ADV/web-engineering co. — разработка и развити...,"['Python', 'ООП', 'Git', 'Docker', 'Elasticsea...",ADV/web-engineering,https://hh.ru/vacancy/70348684,NaN,NaN,NaN
69,69988089,Python разработчик,Москва,От 3 до 6 лет,В ведущей международной табачной компании откр...,"['Python', 'Django Framework', 'MS SQL', 'MLOps']",ANCOR,https://hh.ru/vacancy/69988089,NaN,NaN,NaN
31,70727177,Преподаватель по Data Science на Python,Алматы,От 3 до 6 лет,Мы активно развивающаяся онлайн-школа Academic...,"['Python', 'Грамотная речь', 'Работа с людьми'...",Academica,https://hh.ru/vacancy/70727177,1000000.0,NaN,KZT
...,...,...,...,...,...,...,...,...,...,...,...
80,69888562,Разработчик Python (senior),Москва,От 3 до 6 лет,Наша команда каждый день работает над повышени...,"['Python', 'Django Framework', 'Git', 'Linux',...",билайн,https://hh.ru/vacancy/69888562,NaN,NaN,NaN
77,70811041,Дата инженер,Москва,От 3 до 6 лет,В команду проекта «ERP Data flow» нужен Дата и...,"['Python', 'Hadoop', 'PostgreSQL', 'Linux', 'E...",билайн,https://hh.ru/vacancy/70811041,NaN,NaN,NaN
17,70588588,"Python Django разработчик, удаленно",Самара,От 3 до 6 лет,Мы ищем опытного Python/django fullstack разра...,"['Python', 'Django Framework', 'React']",эдмин,https://hh.ru/vacancy/70588588,150000.0,200000.0,RUR
11,70588587,"Python Django разработчик, удаленно",Екатеринбург,От 3 до 6 лет,Мы ищем опытного Python/django fullstack разра...,"['Python', 'Django Framework', 'React']",эдмин,https://hh.ru/vacancy/70588587,150000.0,200000.0,RUR
23,70588586,"Python Django разработчик, удаленно",Новосибирск,От 3 до 6 лет,Мы ищем опытного Python/django fullstack разра...,"['Python', 'Django Framework', 'React']",эдмин,https://hh.ru/vacancy/70588586,150000.0,200000.0,RUR

In [63]:
df.to_csv('../data/result_deep_sorted.csv', index=False)